name: PHP 7.x Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 7.3, 7.2, 7.1]
        laravel: [8.*, 7.*, 6.*, 5.8.*, 5.7.*, 5.6.* 5.5.*]
        include:
          - laravel: 8.*
            testbench: ^6.0
            phpunit: 9.3
          - laravel: 7.*
            testbench: ^5.0
            phpunit: 8.5
          - laravel: 6.*
            testbench: ^4.0
            phpunit: 8.5
          - laravel: 5.8.*
            testbench: ^3.8
            phpunit: 7.5
          - laravel: 5.7.*
            testbench: ^3.7
            phpunit: 7.0
          - laravel: 5.6.*
            testbench: ^3.6
            phpunit: 7.0
          - laravel: 5.5.*
            testbench: ^3.5
            phpunit: 6.0
        exclude:
          - laravel: 8.*
            php: 7.2
          - laravel: 8.*
            php: 7.1
          - laravel: 7.*
            php: 7.1
          - laravel: 6.*
            php: 7.1
          - laravel: 5.7.*
            php: 7.4
          - laravel: 5.6.*
            php: 7.4
          - laravel: 5.6.*
            php: 7.3
          - laravel: 5.5.*
            php: 7.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: $p{{ matrix.php }}-l{{ matrix.laravel }}-composer-${{ hashFiles('**/composer.json') }}
            restore-keys: $p{{ matrix.php }}-l{{ matrix.laravel }}-composer-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Setup PCOV
        if: ${{ matrix.phpunit < 8 }}
        run: |
          composer require pcov/clobber
          vendor/bin/pcov clobber

      - name: Execute tests
        run: vendor/bin/phpunit --verbose --whitelist=src --coverage-clover=build/coverage/coverage.clover

      - name: Upload coverage
        uses: sudo-bot/action-scrutinizer@latest
        with:
          cli-args: "--format=php-clover build/coverage/coverage.clover"

